import { zipSync, strToU8 } from "fflate";
import baseP2S from "../data/bambu-base-p2s-0.4.json";
import baseA1 from "../data/bambu-base-a1-0.4.json";
import baseA1Mini from "../data/bambu-base-a1-mini-0.4.json";
import baseP1S from "../data/bambu-base-p1s-0.4.json";
import baseX1C from "../data/bambu-base-x1c-0.4.json";
import type { IndexedMesh } from "./mesh";
import { diagnoseMesh, ensureOutwardOrientation, meshBounds, seatOnPlate } from "./mesh";

/**
 * Writes a genuine Bambu Studio project file.
 *
 * CaseFoundry 2026.8.0 exported with @jscad/3mf-serializer, which emits a bare
 * mesh-only 3MF. Bambu Studio then opened it with generic defaults, so every
 * tuned print parameter the app displayed was silently discarded on the way
 * out. This module instead emits the full project: a complete
 * project_settings.config, per-object model_settings.config, and the OPC
 * relationship graph Bambu expects.
 *
 * The 572-key base config is lifted verbatim from a print-verified P2S project
 * (src/data/bambu-p2s-04-base.json) rather than assembled from guesses. Only
 * the keys we genuinely know how to set are overridden.
 */

type ConfigValue = string | string[] | number | boolean | null;
type ProjectConfig = Record<string, ConfigValue>;

/**
 * One base project per supported printer, generated by
 * scripts/build-printer-bases.mjs from Bambu's own machine and process
 * profiles. Exporting a P2S project to an A1 owner was simply wrong: different
 * bed, different kinematics, different start and end gcode.
 */
export const PRINTERS = {
  "p2s-0.4": {
    id: "p2s-0.4",
    name: "Bambu Lab P2S",
    nozzle: 0.4,
    config: baseP2S as unknown as ProjectConfig,
  },
  "a1-0.4": {
    id: "a1-0.4",
    name: "Bambu Lab A1",
    nozzle: 0.4,
    config: baseA1 as unknown as ProjectConfig,
  },
  "a1-mini-0.4": {
    id: "a1-mini-0.4",
    name: "Bambu Lab A1 mini",
    nozzle: 0.4,
    config: baseA1Mini as unknown as ProjectConfig,
  },
  "p1s-0.4": {
    id: "p1s-0.4",
    name: "Bambu Lab P1S",
    nozzle: 0.4,
    config: baseP1S as unknown as ProjectConfig,
  },
  "x1c-0.4": {
    id: "x1c-0.4",
    name: "Bambu Lab X1 Carbon",
    nozzle: 0.4,
    config: baseX1C as unknown as ProjectConfig,
  },
} as const;

export type PrinterId = keyof typeof PRINTERS;

export const DEFAULT_PRINTER: PrinterId = "p2s-0.4";

/**
 * Centre of the build plate, read from the printer's own printable_area rather
 * than assumed. The A1 mini is 180 mm, not 256, so a hardcoded centre would
 * place every part off the plate.
 */
function plateCentre(config: ProjectConfig): { x: number; y: number } {
  const area = config.printable_area;
  if (Array.isArray(area) && area.length) {
    let maxX = 0;
    let maxY = 0;
    for (const corner of area) {
      const [x, y] = String(corner).split("x").map(Number);
      if (Number.isFinite(x) && x > maxX) maxX = x;
      if (Number.isFinite(y) && y > maxY) maxY = y;
    }
    if (maxX > 0 && maxY > 0) return { x: maxX / 2, y: maxY / 2 };
  }
  // Every supported printer publishes printable_area; this is a last resort.
  return { x: 128, y: 128 };
}

/**
 * The Application metadata string in 3dmodel.model MUST look like
 * "BambuStudio-<version>".
 *
 * Bambu Studio parses a version out of this field and dereferences the result
 * without checking it. Writing an honest producer name such as "CaseFoundry"
 * makes the slicer segfault (exit 139) the moment the project is opened, with
 * no error message. Verified by bisection: swapping only this one file into a
 * known-good project reproduced the crash, and changing only this one string
 * fixed it.
 *
 * The real producer is recorded in the Origin field instead, so provenance is
 * kept without tripping the parser.
 */
const BAMBU_APPLICATION_TAG = "BambuStudio-02.08.01.55";

export interface FilamentChoice {
  /** Bambu preset name, e.g. "Bambu PETG Translucent @BBL P2S 0.4 nozzle". */
  name: string;
  /** Bambu preset id, e.g. "GFSG01_13". Names the PRESET. */
  settingId: string | null;
  /** Bambu material id, e.g. "GFG01". Names the MATERIAL, a different
   * namespace to settingId. This is what filament_ids expects. */
  filamentId: string | null;
  type: string;
  nozzleTemp: number;
  nozzleTempInitialLayer: number;
  bedTemp: number;
  bedPlate: string;
  flowRatio?: number;
  maxVolumetricSpeed?: number;
  retractionLength?: number;
  density?: number;
  costPerKg?: number;
  fanMin?: number;
  fanMax?: number;
  slowDownMinSpeed?: number;
  /** Display colour for the plate preview. */
  colour?: string;
}

export interface PrintRecipe {
  id: string;
  name: string;
  layerHeight: number;
  initialLayerHeight: number;
  wallLoops: number;
  topShellLayers: number;
  bottomShellLayers: number;
  sparseInfillDensity: string;
  sparseInfillPattern: string;
  outerWallSpeed: number;
  innerWallSpeed: number;
  sparseInfillSpeed: number;
  internalSolidInfillSpeed: number;
  topSurfaceSpeed: number;
  gapInfillSpeed: number;
  smallPerimeterSpeed: number;
  initialLayerSpeed: number;
  /** Part cooling fan, percent. */
  fanMinSpeed: number;
  fanMaxSpeed: number;
  overhangFanSpeed: number;
  closeFanFirstLayers: number;
  enableSupport: boolean;
  brimType: string;
}

/**
 * Recipes recovered verbatim from two print-verified project files.
 * These are measured settings from files that printed well, not defaults.
 */
export const RECIPES: Record<string, PrintRecipe> = {
  /** From Galaxy_S24_Plus_Asanoha_Kumiko_Glass_P2S_PETG_Translucent.3mf */
  "translucent-glass": {
    id: "translucent-glass",
    name: "Translucent glass (buried lattice)",
    layerHeight: 0.1,
    initialLayerHeight: 0.2,
    // One wall and zero shells with 100% infill is what makes the buried
    // lattice read as glass: the whole wall becomes a single clean extrusion.
    wallLoops: 1,
    topShellLayers: 0,
    bottomShellLayers: 0,
    sparseInfillDensity: "100%",
    sparseInfillPattern: "zig-zag",
    outerWallSpeed: 20,
    innerWallSpeed: 20,
    sparseInfillSpeed: 20,
    internalSolidInfillSpeed: 20,
    topSurfaceSpeed: 20,
    gapInfillSpeed: 20,
    smallPerimeterSpeed: 20,
    initialLayerSpeed: 20,
    // Cooling is deliberately OFF. Layers fuse into an optically continuous
    // wall, which is what makes the buried lattice read as glass rather than
    // as a stack of visible lines.
    fanMinSpeed: 0,
    fanMaxSpeed: 0,
    overhangFanSpeed: 0,
    closeFanFirstLayers: 1,
    enableSupport: false,
    brimType: "outer_only",
  },
  /** From Galaxy_A52_A52s_Asanoha_Kumiko_Engraved_P2S_PLA_Solid.3mf */
  "solid-engraved": {
    id: "solid-engraved",
    name: "Solid engraved",
    layerHeight: 0.16,
    initialLayerHeight: 0.2,
    wallLoops: 3,
    topShellLayers: 4,
    bottomShellLayers: 4,
    sparseInfillDensity: "20%",
    sparseInfillPattern: "gyroid",
    outerWallSpeed: 60,
    innerWallSpeed: 100,
    sparseInfillSpeed: 100,
    internalSolidInfillSpeed: 80,
    topSurfaceSpeed: 50,
    gapInfillSpeed: 50,
    smallPerimeterSpeed: 40,
    initialLayerSpeed: 20,
    // Cooling ON. The base project this writer starts from is the translucent
    // glass one, which runs the fans OFF on purpose. Inheriting that for a
    // normal rigid print gives drooping overhangs and poor layer definition,
    // so every non-glass recipe must state its own cooling explicitly.
    fanMinSpeed: 80,
    fanMaxSpeed: 100,
    overhangFanSpeed: 100,
    closeFanFirstLayers: 2,
    enableSupport: false,
    brimType: "outer_only",
  },
};

/**
 * Replaces an array-valued config key while preserving its own length.
 *
 * Bambu configs mix array lengths across filament keys in the same file
 * (filament_type has one entry while nozzle_temperature has two). Normalising
 * every key to one key's length corrupts the project, so each key keeps its
 * own arity and simply repeats the new value.
 */
function setPerSlot(config: ProjectConfig, key: string, value: string): void {
  const existing = config[key];
  if (Array.isArray(existing)) {
    config[key] = existing.map(() => value);
  } else if (existing !== undefined) {
    config[key] = value;
  }
  // A key absent from the base config is not invented here.
}

/**
 * Bambu stores bed temperature per plate type and reads the one named by
 * curr_bed_type. Set the active plate's temperature and leave the rest alone.
 */
const PLATE_TEMP_KEYS: Record<string, string> = {
  "Textured PEI Plate": "textured_plate_temp",
  "High Temp Plate": "hot_plate_temp",
  "Engineering Plate": "eng_plate_temp",
  "Cool Plate": "cool_plate_temp",
  "Cool Plate SuperTack": "supertack_plate_temp",
};

export function buildProjectConfig(
  filament: FilamentChoice,
  recipe: PrintRecipe,
  printer: PrinterId = DEFAULT_PRINTER,
): ProjectConfig {
  const config: ProjectConfig = JSON.parse(
    JSON.stringify(PRINTERS[printer].config),
  );

  // --- filament ---------------------------------------------------------
  setPerSlot(config, "filament_type", filament.type);
  setPerSlot(config, "filament_settings_id", filament.name);
  // filament_ids takes the MATERIAL id (GFA00), never the preset id
  // (GFSA00_11). They are separate namespaces with no overlap across the whole
  // shipped profile library, so writing the preset id here labels the project
  // with a filament that does not exist.
  if (filament.filamentId) setPerSlot(config, "filament_ids", filament.filamentId);
  setPerSlot(config, "nozzle_temperature", String(filament.nozzleTemp));
  setPerSlot(
    config,
    "nozzle_temperature_initial_layer",
    String(filament.nozzleTempInitialLayer),
  );
  if (filament.flowRatio !== undefined)
    setPerSlot(config, "filament_flow_ratio", String(filament.flowRatio));
  if (filament.maxVolumetricSpeed !== undefined)
    setPerSlot(
      config,
      "filament_max_volumetric_speed",
      String(filament.maxVolumetricSpeed),
    );
  if (filament.retractionLength !== undefined)
    setPerSlot(
      config,
      "filament_retraction_length",
      String(filament.retractionLength),
    );
  if (filament.density !== undefined)
    setPerSlot(config, "filament_density", String(filament.density));
  if (filament.costPerKg !== undefined)
    setPerSlot(config, "filament_cost", String(filament.costPerKg));
  if (filament.slowDownMinSpeed !== undefined)
    setPerSlot(config, "slow_down_min_speed", String(filament.slowDownMinSpeed));
  if (filament.colour) {
    setPerSlot(config, "filament_colour", filament.colour);
    setPerSlot(config, "default_filament_colour", filament.colour);
  }

  // --- bed --------------------------------------------------------------
  const plateKey = PLATE_TEMP_KEYS[filament.bedPlate];
  if (plateKey) {
    setPerSlot(config, plateKey, String(filament.bedTemp));
    setPerSlot(config, `${plateKey}_initial_layer`, String(filament.bedTemp));
    config.curr_bed_type = filament.bedPlate;
  }

  // --- process ----------------------------------------------------------
  // Bambu stores every scalar setting as a STRING, never a JSON number. Writing
  // a real number makes the slicer log "invalid json type for <key>" and fall
  // back to its own default, silently discarding the setting.
  config.layer_height = String(recipe.layerHeight);
  config.initial_layer_print_height = String(recipe.initialLayerHeight);
  config.wall_loops = String(recipe.wallLoops);
  config.top_shell_layers = String(recipe.topShellLayers);
  config.bottom_shell_layers = String(recipe.bottomShellLayers);
  config.sparse_infill_density = recipe.sparseInfillDensity;
  config.sparse_infill_pattern = recipe.sparseInfillPattern;
  setPerSlot(config, "outer_wall_speed", String(recipe.outerWallSpeed));
  setPerSlot(config, "inner_wall_speed", String(recipe.innerWallSpeed));
  setPerSlot(config, "sparse_infill_speed", String(recipe.sparseInfillSpeed));
  setPerSlot(
    config,
    "internal_solid_infill_speed",
    String(recipe.internalSolidInfillSpeed),
  );
  setPerSlot(config, "top_surface_speed", String(recipe.topSurfaceSpeed));
  setPerSlot(config, "gap_infill_speed", String(recipe.gapInfillSpeed));
  setPerSlot(config, "small_perimeter_speed", String(recipe.smallPerimeterSpeed));
  setPerSlot(config, "initial_layer_speed", String(recipe.initialLayerSpeed));

  // Cooling must come from the recipe, never inherited. The base project is the
  // translucent-glass one and runs its fans off by design.
  setPerSlot(config, "fan_min_speed", String(recipe.fanMinSpeed));
  setPerSlot(config, "fan_max_speed", String(recipe.fanMaxSpeed));
  setPerSlot(config, "overhang_fan_speed", String(recipe.overhangFanSpeed));
  setPerSlot(
    config,
    "close_fan_the_first_x_layers",
    String(recipe.closeFanFirstLayers),
  );
  config.enable_support = recipe.enableSupport ? "1" : "0";
  config.brim_type = recipe.brimType;
  config.print_settings_id = recipe.name;

  return config;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Deterministic RFC-4122-shaped identifier.
 *
 * Bambu only requires these to be well formed and internally consistent, so a
 * seeded generator is used instead of randomness: exporting the same case twice
 * then produces byte-identical files, which makes diffing and checksums useful.
 */
function seededUuid(seed: string, salt: number): string {
  let h1 = 0x811c9dc5 ^ salt;
  for (let index = 0; index < seed.length; index += 1) {
    h1 ^= seed.charCodeAt(index);
    h1 = Math.imul(h1, 0x01000193) >>> 0;
  }
  const hex = (rounds: number) => {
    let out = "";
    let state = h1;
    for (let index = 0; index < rounds; index += 1) {
      state = Math.imul(state ^ (state >>> 15), 0x2545f491) >>> 0;
      out += state.toString(16).padStart(8, "0");
    }
    return out;
  };
  const digits = hex(4).slice(0, 32);
  return [
    digits.slice(0, 8),
    digits.slice(8, 12),
    `4${digits.slice(13, 16)}`,
    `a${digits.slice(17, 20)}`,
    digits.slice(20, 32),
  ].join("-");
}

function meshToObjectModel(mesh: IndexedMesh, uuid: string): string {
  const { positions, indices } = mesh;

  const vertices: string[] = [];
  for (let index = 0; index < positions.length; index += 3) {
    vertices.push(
      `<vertex x="${+positions[index].toFixed(6)}" y="${+positions[index + 1].toFixed(6)}" z="${+positions[index + 2].toFixed(6)}"/>`,
    );
  }

  const triangles: string[] = [];
  for (let index = 0; index < indices.length; index += 3) {
    triangles.push(
      `<triangle v1="${indices[index]}" v2="${indices[index + 1]}" v3="${indices[index + 2]}"/>`,
    );
  }

  return `<?xml version='1.0' encoding='utf-8'?>
<model xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06" unit="millimeter" xml:lang="en-US" requiredextensions="p">
 <metadata name="BambuStudio:3mfVersion">1</metadata>
 <resources>
  <object id="1" p:UUID="${uuid}" type="model">
   <mesh>
    <vertices>${vertices.join("")}</vertices>
    <triangles>${triangles.join("")}</triangles>
   </mesh>
  </object>
 </resources>
 <build/>
</model>
`;
}

export interface ProjectMetadata {
  /** Shown as the object name in Bambu Studio. */
  title: string;
  /** Shown on the plate tab. */
  plateName: string;
  /** Free text describing what this case is and where its fit came from. */
  description: string;
  /** Human summary of the print recipe. */
  profileDescription: string;
  /** ISO date, e.g. "2026-08-09". Passed in so exports stay reproducible. */
  date: string;
}

export interface BambuProjectResult {
  bytes: Uint8Array;
  diagnostics: ReturnType<typeof diagnoseMesh>;
  bounds: ReturnType<typeof meshBounds>;
}

/**
 * Serialises a case into a Bambu Studio project.
 *
 * Throws when the mesh is not watertight. An unslicable export is a defect, and
 * 2026.8.0 shipped several because nothing checked before writing the file.
 */
export function buildBambuProject(options: {
  mesh: IndexedMesh;
  filament: FilamentChoice;
  recipe: PrintRecipe;
  metadata: ProjectMetadata;
  /** Which printer this project is for. Defaults to the P2S. */
  printer?: PrinterId;
  /** Skip the watertight gate. Only for inspecting a known-bad mesh. */
  allowNonManifold?: boolean;
}): BambuProjectResult {
  const seated = seatOnPlate(ensureOutwardOrientation(options.mesh));
  const diagnostics = diagnoseMesh(seated);

  if (!options.allowNonManifold) {
    if (!diagnostics.isEdgeManifold) {
      throw new Error(
        `Mesh is not watertight: ${diagnostics.boundaryEdges} boundary edges, ` +
          `${diagnostics.nonManifoldEdges} non-manifold edges. Bambu Studio ` +
          `cannot slice this reliably, so it was not exported.`,
      );
    }
    if (!diagnostics.isConsistentlyOriented) {
      throw new Error(
        "Mesh has inconsistent triangle winding, so inside and outside are " +
          "ambiguous. Refusing to export.",
      );
    }
  }

  const printer = options.printer ?? DEFAULT_PRINTER;
  const config = buildProjectConfig(options.filament, options.recipe, printer);
  const centre = plateCentre(config);
  const bounds = meshBounds(seated);
  const seed = `${options.metadata.title}|${options.filament.name}|${options.recipe.id}|${printer}`;

  const objectUuid = seededUuid(seed, 1);
  const componentUuid = seededUuid(seed, 2);
  const wrapperUuid = seededUuid(seed, 3);
  const buildUuid = seededUuid(seed, 4);
  const itemUuid = seededUuid(seed, 5);
  const partUuid = seededUuid(seed, 6);

  const modelXml = `<?xml version='1.0' encoding='utf-8'?>
<model xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06" unit="millimeter" xml:lang="en-US" requiredextensions="p">
 <metadata name="Application">${BAMBU_APPLICATION_TAG}</metadata>
 <metadata name="BambuStudio:3mfVersion">1</metadata>
 <metadata name="Origin">CaseFoundry</metadata>
 <metadata name="CreationDate">${options.metadata.date}</metadata>
 <metadata name="ModificationDate">${options.metadata.date}</metadata>
 <metadata name="Description">${escapeXml(options.metadata.description)}</metadata>
 <metadata name="ProfileDescription">${escapeXml(options.metadata.profileDescription)}</metadata>
 <metadata name="ProfileTitle">${escapeXml(options.recipe.name)}</metadata>
 <metadata name="Title">${escapeXml(options.metadata.title)}</metadata>
 <resources>
  <object id="2" p:UUID="${wrapperUuid}" type="model">
   <components>
    <component p:path="/3D/Objects/object_1.model" objectid="1" p:UUID="${componentUuid}" transform="1 0 0 0 1 0 0 0 1 0 0 0"/>
   </components>
  </object>
 </resources>
 <build p:UUID="${buildUuid}">
  <item objectid="2" p:UUID="${itemUuid}" transform="1 0 0 0 1 0 0 0 1 ${centre.x} ${centre.y} 0" printable="1"/>
 </build>
</model>
`;

  const modelSettingsXml = `<?xml version='1.0' encoding='utf-8'?>
<config>
  <object id="2">
    <metadata key="name" value="${escapeXml(options.metadata.title)}"/>
    <metadata key="extruder" value="1"/>
    <metadata face_count="${seated.triangleCount}"/>
    <part id="1" subtype="normal_part" uuid="${partUuid}">
      <metadata key="name" value="${escapeXml(options.metadata.title)}"/>
      <metadata key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>
      <metadata key="source_file" value="${escapeXml(options.metadata.title)}.3mf"/>
      <metadata key="source_object_id" value="0"/>
      <metadata key="source_volume_id" value="0"/>
      <metadata key="source_offset_x" value="0"/>
      <metadata key="source_offset_y" value="0"/>
      <metadata key="source_offset_z" value="0"/>
      <mesh_stat face_count="${seated.triangleCount}" edges_fixed="0" degenerate_facets="${diagnostics.degenerateTriangles}" facets_removed="0" facets_reversed="0" backwards_edges="0"/>
    </part>
  </object>
  <plate>
    <metadata key="plater_id" value="1"/>
    <metadata key="plater_name" value="${escapeXml(options.metadata.plateName)}"/>
    <metadata key="locked" value="false"/>
    <metadata key="filament_map_mode" value="Auto For Flush"/>
    <metadata key="gcode_file" value=""/>
    <model_instance>
      <metadata key="object_id" value="2"/>
      <metadata key="instance_id" value="0"/>
      <metadata key="identify_id" value="1"/>
    </model_instance>
  </plate>
</config>
`;

  const contentTypes = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
 <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
 <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
 <Default Extension="png" ContentType="image/png"/>
 <Default Extension="gcode" ContentType="text/x.gcode"/>
</Types>
`;

  // No thumbnail relationships are declared because CaseFoundry does not write
  // plate PNGs. Pointing at a file that is not in the archive makes Bambu
  // Studio report a damaged project; it renders its own preview on open.
  const rootRels = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
 <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
`;

  const modelRels = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
 <Relationship Target="/3D/Objects/object_1.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
`;

  const customGcode = `<?xml version='1.0' encoding='utf-8'?>
<custom_gcodes_per_layer><plate><plate_info id="1"/><mode value="SingleExtruder"/></plate></custom_gcodes_per_layer>
`;

  const files: Record<string, Uint8Array> = {
    "[Content_Types].xml": strToU8(contentTypes),
    "_rels/.rels": strToU8(rootRels),
    "3D/3dmodel.model": strToU8(modelXml),
    "3D/_rels/3dmodel.model.rels": strToU8(modelRels),
    "3D/Objects/object_1.model": strToU8(meshToObjectModel(seated, objectUuid)),
    "Metadata/project_settings.config": strToU8(JSON.stringify(config, null, 4)),
    "Metadata/model_settings.config": strToU8(modelSettingsXml),
    "Metadata/custom_gcode_per_layer.xml": strToU8(customGcode),
  };

  return { bytes: zipSync(files, { level: 6 }), diagnostics, bounds };
}
